version: "3.8"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-serverBD
    environment:
      SA_PASSWORD: SQL#1234
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
