# Usa una imagen base de Java
FROM openjdk:11-jre-slim

# Instalar Maven
RUN apt-get update && apt-get install -y maven

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo pom.xml para descargar las dependencias
COPY pom.xml .

# Descarga las dependencias de Maven
RUN mvn dependency:go-offline

# Copia el resto de la aplicación
COPY . .

# Compila la aplicación
RUN mvn package

# Expone el puerto en el que se ejecuta tu aplicación
EXPOSE 9000

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "gestiones.jar"]
